"""
TODO:
    MAKE SCRIPT THAT DOES THE FOLLOWING:
    - REMOVE HADA FROM HANGUL AND HANJA IF IT EXISTS (CHECK THE HANJA STRING)
    - MAKE (HANGUL SUBSEQ, HANJA SUBSEQ) TUPLES FOR EACH SUBSEQ FROM THE STRING
    - MAKE COLUMN WITH NUMBER OF HANGUL SUBSEQ & NUMBER OF HANJA SUBSEQ
    - SORT VALUES IN VARIOUS WAYS
"""

#https://developers.naver.com/docs/papago/papago-nmt-api-reference.md

# Naver Client ID: WyPCRsYaxeKJ748sfFdV
# Naver Client secret: EFpX_fxYpo